# inherit_gem:
#   # Omakase Ruby styling for Rails https://github.com/rails/rubocop-rails-omakase/
#   rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
    - doc/**/*
    - project-files/**/*
    - .trunk/**/*
    - .ruby-lsp/**/*
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.4

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/LineLength:
  AllowHeredoc: true
  AllowURI: true
  AllowedPatterns: []
  IgnoreCopDirectives: false
  Max: 100
  URISchemes:
    - http
    - https
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  AllowedMethods:
    - group
    - define
Metrics/ClassLength:
  CountAsOne: [array, heredoc]
Metrics/MethodLength:
  AllowedMethods: []
  CountAsOne: [array, heredoc]
  Max: 12
Metrics/ModuleLength:
  CountAsOne: [array, heredoc]

Rails:
  Enabled: true
Rails/TimeZone:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true